### PR TITLE
Updating docs

### PR DESCRIPTION
**Pull request by alydersen**
Better docs

### CODE REVIEW

**Review by sleiban — CHANGES_REQUESTED** [review]
<p>Ping your Config Repository to check for a valid response</p>
->
<p>Ping your EDGE/APIS to check for a valid response</p>

This comment was correct before. You can ping a CR not an Edge.
Also consider changeing the name from ping-namespace to just ping. Does not make sense to ping a namespace

**Comment by alydersen** [comment]
@sleiban I'm not sure you are correct here. The EdgeManagment.proto file has a ping command and it seems like this is the one used. That means we are pinging the EdgeManagementService if I'm not mistaken.

**Comment by alydersen** [comment]
@sleiban Renamed ping-namespace to just ping

**Review by sleiban — APPROVED** [review]
Ok, I was mixing CR and EM.

**Pull request merged**
